import type { Project, Step } from "@/types/project";

export const steps: Step[] = [
  {
    title: "아이디어 입력",
    shortTitle: "아이디어 입력",
    icon: "idea",
    question: "가장 가까운 서비스 아이디어를 고르고, 필요한 부분만 고쳐주세요.",
    helper: "처음부터 완벽히 쓰지 않아도 됩니다. 선택지를 눌러 초안을 만들고, 내 상황에 맞게 조금만 수정하세요.",
    inputs: [
      {
        id: "serviceName",
        label: "서비스 이름 (가칭)",
        placeholder: "예: 소상공인을 위한 AI 블로그 자동화 서비스",
        maxLength: 80,
        required: true,
        options: [
          "AI 블로그 자동화 서비스",
          "예약 관리 서비스",
          "고객 문의 자동응답 서비스",
          "개인 맞춤 학습 도우미",
        ],
      },
      {
        id: "serviceDescription",
        label: "서비스 설명",
        placeholder: "예: 키워드만 입력하면 AI가 글 제목, 목차, 본문 초안을 자동으로 생성해주는 서비스",
        multiline: true,
        maxLength: 500,
        required: true,
        options: [
          "키워드만 입력하면 결과물을 자동으로 만들어주는 서비스",
          "반복 업무를 체크리스트와 자동화로 줄여주는 서비스",
          "초보자가 단계별 질문에 답하면 결과 문서를 만들어주는 서비스",
          "고객 데이터를 한 화면에서 정리하고 다음 행동을 추천하는 서비스",
        ],
      },
      {
        id: "problem",
        label: "해결하고 싶은 문제",
        placeholder: "예: 블로그 글쓰기에 시간과 노력이 많이 들고 꾸준히 작성하기 어렵다.",
        multiline: true,
        maxLength: 500,
        options: [
          "시간이 부족해서 꾸준히 하기 어렵다.",
          "무엇부터 시작해야 할지 몰라 막힌다.",
          "반복 작업이 많아 실수가 생긴다.",
          "여러 도구에 정보가 흩어져 관리하기 어렵다.",
        ],
      },
      {
        id: "goal",
        label: "이 서비스로 이루고 싶은 목표",
        placeholder: "예: 누구나 쉽고 빠르게 블로그 글을 작성해 온라인 마케팅을 할 수 있도록 돕는다.",
        multiline: true,
        maxLength: 500,
        options: [
          "초보자도 10분 안에 첫 결과물을 만들게 한다.",
          "반복 업무 시간을 절반 이하로 줄인다.",
          "전문가 도움 없이도 의사결정할 수 있게 돕는다.",
          "사용자가 다음 행동을 바로 실행할 수 있게 만든다.",
        ],
      },
    ],
  },
  {
    title: "타겟 · 문제 정의",
    shortTitle: "타겟 · 문제 정의",
    icon: "users",
    question: "누가 가장 절실하게 이 서비스를 필요로 하나요?",
    helper: "타겟은 넓게 잡기보다 한 사람처럼 구체적으로 잡는 편이 좋습니다.",
    inputs: [
      {
        id: "targetUser",
        label: "핵심 사용자",
        placeholder: "예: 온라인 마케팅 경험이 적은 1인 가게 사장님",
        required: true,
        options: [
          "1인 사업자",
          "소상공인",
          "초기 스타트업 팀",
          "비전공자 창업자",
          "프리랜서",
        ],
      },
      {
        id: "userSituation",
        label: "사용자 상황",
        placeholder: "예: 매장 운영이 바빠 콘텐츠를 꾸준히 만들 시간이 부족하다.",
        multiline: true,
        options: [
          "혼자 여러 업무를 동시에 처리하고 있다.",
          "예산이 적어 전문가를 고용하기 어렵다.",
          "디지털 도구 사용 경험이 많지 않다.",
          "빨리 검증해야 하지만 개발 지식이 부족하다.",
        ],
      },
      {
        id: "painPoints",
        label: "페인포인트",
        placeholder: "예: 무엇을 써야 할지 모르고, 글을 완성하는 데 시간이 오래 걸린다.",
        multiline: true,
        options: [
          "시작점이 막막하다.",
          "작업 시간이 오래 걸린다.",
          "결과 품질이 들쭉날쭉하다.",
          "기존 도구가 너무 복잡하다.",
        ],
      },
    ],
  },
  {
    title: "서비스 형태 선택",
    shortTitle: "서비스 형태 선택",
    icon: "screen",
    question: "사용자는 어떤 형태로 이 서비스를 만나면 좋을까요?",
    helper: "MVP에서는 가장 빠르게 만들고 테스트할 수 있는 형태를 고르는 것이 좋습니다.",
    inputs: [
      {
        id: "serviceType",
        label: "서비스 형태",
        placeholder: "예: 로그인 없는 웹 기반 마법사형 SaaS MVP",
        required: true,
        options: [
          "단계형 Wizard",
          "대시보드",
          "챗봇",
          "문서 생성기",
          "체크리스트 도구",
        ],
      },
      {
        id: "platform",
        label: "주요 플랫폼",
        placeholder: "예: 데스크톱 웹 우선, 모바일 대응",
        options: [
          "데스크톱 웹 우선",
          "모바일 웹 우선",
          "반응형 웹",
          "크롬 확장",
          "모바일 앱",
        ],
      },
    ],
  },
  {
    title: "레퍼런스 분석",
    shortTitle: "레퍼런스 분석",
    icon: "search",
    question: "어떤 서비스의 흐름이나 느낌을 참고하면 좋을까요?",
    helper: "정확한 URL이 없어도 괜찮습니다. 닮고 싶은 사용 경험을 고르면 됩니다.",
    inputs: [
      {
        id: "references",
        label: "참고 서비스·URL",
        placeholder: "예: Typeform, Notion AI, Wix ADI",
        multiline: true,
        options: ["Typeform", "Notion", "Canva", "Wix ADI", "Tally", "Airtable"],
      },
      {
        id: "referenceNotes",
        label: "참고할 점",
        placeholder: "예: 단계형 입력은 Typeform처럼 간단하게, 결과 문서는 Notion처럼 정리",
        multiline: true,
        options: [
          "단계별 입력이 쉽다.",
          "결과 문서가 보기 좋게 정리된다.",
          "버튼과 선택지가 명확하다.",
          "초보자도 다음 행동을 이해하기 쉽다.",
        ],
      },
    ],
  },
  {
    title: "MVP 기능 정리",
    shortTitle: "MVP 기능 정리",
    icon: "check",
    question: "첫 버전에 꼭 넣을 기능과 빼야 할 기능을 고르세요.",
    helper: "MVP는 작아야 빨리 검증됩니다. 지금 당장 필요한 기능만 남겨봅니다.",
    inputs: [
      {
        id: "mvpFeatures",
        label: "포함할 핵심 기능",
        placeholder: "- 10단계 입력\n- 자동 저장\n- 결과 프롬프트 복사",
        multiline: true,
        required: true,
        options: [
          "단계별 입력",
          "선택지 클릭 입력",
          "실시간 요약",
          "LocalStorage 자동 저장",
          "최종 프롬프트 복사",
          "모바일 대응",
        ],
      },
      {
        id: "excludedFeatures",
        label: "이번 버전에서 제외할 기능",
        placeholder: "- 로그인\n- 결제\n- 실시간 협업\n- 서버 저장",
        multiline: true,
        options: ["로그인", "결제", "팀 협업", "서버 저장", "AI 자동 분석", "관리자 페이지"],
      },
    ],
  },
  {
    title: "화면 구조 설계",
    shortTitle: "화면 구조 설계",
    icon: "layout",
    question: "사용자가 보는 화면은 어떤 구조가 좋을까요?",
    helper: "초보자는 화면 이름보다 역할로 생각하면 쉽습니다. 입력, 요약, 결과, 복사 같은 역할을 고르세요.",
    inputs: [
      {
        id: "screens",
        label: "주요 화면 목록",
        placeholder: "예: 랜딩, Wizard 입력, 현재까지 입력된 내용, 최종 결과",
        multiline: true,
        options: ["시작 화면", "단계별 입력 화면", "실시간 요약 패널", "최종 결과 화면", "설정 화면"],
      },
      {
        id: "userJourney",
        label: "사용자 흐름",
        placeholder: "예: 목적 확인 → 10단계 입력 → 결과 확인 → 프롬프트 복사",
        multiline: true,
        options: [
          "목적 확인 → 선택지 클릭 → 보충 입력 → 결과 복사",
          "아이디어 입력 → MVP 정리 → 개발 프롬프트 생성",
          "단계별 저장 → 새로고침 후 복원 → 최종 내보내기",
        ],
      },
    ],
  },
  {
    title: "데이터 · API 설계",
    shortTitle: "데이터 · API 설계",
    icon: "data",
    question: "MVP에서 저장해야 할 정보와 API 필요 여부를 고르세요.",
    helper: "처음에는 서버 없이 브라우저 저장만으로도 충분한 경우가 많습니다.",
    inputs: [
      {
        id: "dataModel",
        label: "저장 데이터",
        placeholder: "예: Project 객체, currentStep, 입력 완료 상태",
        multiline: true,
        options: ["Project 입력값", "현재 단계", "완료 상태", "생성된 프롬프트", "사용자 설정"],
      },
      {
        id: "apiNeeds",
        label: "API 필요 여부",
        placeholder: "예: v1에서는 API 없음. 2차에서 AI API와 Supabase 연동",
        multiline: true,
        options: [
          "v1에서는 API 없음",
          "OpenAI API 연동 예정",
          "Supabase 저장 예정",
          "인증 API는 2차 버전",
        ],
      },
    ],
  },
  {
    title: "아키텍처 추천",
    shortTitle: "아키텍처 추천",
    icon: "arch",
    question: "어떤 기술 조합으로 시작하면 좋을까요?",
    helper: "초기 MVP는 익숙하고 배포가 쉬운 조합이 좋습니다.",
    inputs: [
      {
        id: "architecture",
        label: "추천 기술 스택",
        placeholder: "예: Next.js, TypeScript, Tailwind, LocalStorage, Vercel",
        multiline: true,
        options: ["Next.js", "TypeScript", "Tailwind CSS", "LocalStorage", "Vercel", "Supabase"],
      },
      {
        id: "constraints",
        label: "개발 제약",
        placeholder: "예: 백엔드는 생략하고 브라우저 중심 정적 웹앱으로 먼저 검증",
        multiline: true,
        options: [
          "백엔드 없이 시작",
          "환경변수는 로컬에만 보관",
          "모바일 360px 지원",
          "빌드 오류 없는 상태로 배포",
        ],
      },
    ],
  },
  {
    title: "프롬프트 생성",
    shortTitle: "프롬프트 생성",
    icon: "doc",
    question: "어떤 AI 개발 도구에 넘길 프롬프트를 만들까요?",
    helper: "도구별로 말투보다 중요한 것은 목표, 범위, 완료 기준을 분명히 적는 것입니다.",
    inputs: [
      {
        id: "promptTarget",
        label: "대상 AI 도구",
        placeholder: "예: Codex, Cursor, Claude",
        options: ["Codex", "Cursor", "Claude", "ChatGPT", "v0"],
      },
      {
        id: "promptPreference",
        label: "프롬프트 스타일",
        placeholder: "예: 파일 구조부터 구현, QA, README 업데이트까지 요청하는 상세 프롬프트",
        multiline: true,
        options: [
          "구현까지 맡기는 상세 프롬프트",
          "디자인만 요청하는 프롬프트",
          "버그 수정 중심 프롬프트",
          "QA와 배포까지 포함한 프롬프트",
        ],
      },
    ],
  },
  {
    title: "배포 · 운영 체크리스트",
    shortTitle: "배포 · 운영 체크리스트",
    icon: "deploy",
    question: "배포 전에 무엇을 확인해야 할까요?",
    helper: "초보자에게는 체크리스트가 가장 안전합니다. 빌드, 환경변수, 모바일, 복사 기능을 확인하세요.",
    inputs: [
      {
        id: "deployment",
        label: "배포 계획",
        placeholder: "예: GitHub 저장소 연결 후 Vercel 배포",
        multiline: true,
        options: ["GitHub에 커밋", "Vercel에 연결", "환경변수 등록", "배포 URL 확인"],
      },
      {
        id: "qaChecklist",
        label: "운영 체크리스트",
        placeholder: "- npm run build\n- 모바일 360px 확인\n- 환경변수 등록\n- 최종 프롬프트 복사 확인",
        multiline: true,
        options: [
          "npm run lint 통과",
          "npm run build 통과",
          "모바일 화면 확인",
          "LocalStorage 복원 확인",
          "프롬프트 복사 확인",
        ],
      },
    ],
  },
];

export const emptyProject: Project = {
  serviceName: "",
  serviceDescription: "",
  problem: "",
  goal: "",
  targetUser: "",
  userSituation: "",
  painPoints: "",
  serviceType: "",
  platform: "",
  references: "",
  referenceNotes: "",
  mvpFeatures: "",
  excludedFeatures: "",
  screens: "",
  userJourney: "",
  dataModel: "",
  apiNeeds: "",
  architecture: "",
  constraints: "",
  promptTarget: "",
  promptPreference: "",
  deployment: "",
  qaChecklist: "",
};
