import type { Project, Step } from "@/types/project";

export const steps: Step[] = [
  {
    id: "idea",
    title: "아이디어 입력",
    shortTitle: "Idea",
    question: "만들고 싶은 서비스 아이디어는 무엇인가요?",
    helper: "한 문장으로 시작해도 괜찮습니다. 누가 어떤 상황에서 쓰는지까지 적으면 더 좋아요.",
    placeholder: "예: 동네 소상공인이 10분 안에 이벤트 랜딩페이지를 만드는 서비스",
    required: true,
  },
  {
    id: "target",
    title: "타겟 사용자 정의",
    shortTitle: "Target",
    question: "가장 먼저 만족시켜야 할 사용자는 누구인가요?",
    helper: "사용자의 직업, 수준, 불편함, 성공 기준을 적어주세요.",
    placeholder: "예: 온라인 마케팅 경험이 적은 1인 가게 사장님",
    required: true,
  },
  {
    id: "serviceType",
    title: "서비스 형태 선택",
    shortTitle: "Type",
    question: "이 아이디어는 어떤 형태의 제품에 가깝나요?",
    helper: "웹앱, 모바일앱, 대시보드, 챗봇, 자동화 도구 등으로 설명해주세요.",
    placeholder: "예: 로그인 없는 웹 기반 마법사형 SaaS MVP",
  },
  {
    id: "references",
    title: "레퍼런스 분석",
    shortTitle: "Refs",
    question: "비슷한 서비스나 참고하고 싶은 화면이 있나요?",
    helper: "URL, 서비스명, 마음에 드는 흐름과 피하고 싶은 점을 함께 적어주세요.",
    placeholder: "예: Typeform의 단계형 입력, Notion의 깔끔한 결과 문서",
  },
  {
    id: "mvpFeatures",
    title: "MVP 기능 정리",
    shortTitle: "MVP",
    question: "처음 버전에 꼭 필요한 기능은 무엇인가요?",
    helper: "있으면 좋은 기능과 반드시 필요한 기능을 분리하면 개발 범위가 또렷해집니다.",
    placeholder: "- 10단계 입력\n- 자동 저장\n- 결과 프롬프트 복사",
    required: true,
  },
  {
    id: "screens",
    title: "화면 구조 설계",
    shortTitle: "Screens",
    question: "사용자가 보게 될 주요 화면은 무엇인가요?",
    helper: "첫 화면, 입력 화면, 결과 화면, 설정 화면처럼 나눠 적어주세요.",
    placeholder: "예: 홈 겸 Wizard, 오른쪽 요약 패널, 최종 결과 패널",
  },
  {
    id: "dataApi",
    title: "데이터 및 API 설계",
    shortTitle: "Data",
    question: "저장해야 할 데이터와 필요한 API가 있나요?",
    helper: "MVP에서는 LocalStorage만으로 충분한지, 서버 API가 필요한지 판단합니다.",
    placeholder: "예: Project 객체를 LocalStorage에 저장. API는 v1에서 제외",
  },
  {
    id: "architecture",
    title: "아키텍처 추천",
    shortTitle: "Arch",
    question: "선호하는 기술 스택이나 제약이 있나요?",
    helper: "배포 위치, 인증 여부, DB 필요 여부, AI API 사용 계획을 적어주세요.",
    placeholder: "예: Next.js, TypeScript, Tailwind, Vercel, 추후 Supabase",
  },
  {
    id: "promptPreference",
    title: "개발 프롬프트 생성",
    shortTitle: "Prompt",
    question: "AI 개발 도구에 어떤 스타일로 요청하고 싶나요?",
    helper: "Cursor, Claude, ChatGPT, Codex 중 대상 도구와 원하는 톤을 적어주세요.",
    placeholder: "예: Codex에게 파일 구조부터 구현까지 맡길 수 있는 상세 프롬프트",
  },
  {
    id: "deployment",
    title: "배포 및 운영 체크리스트",
    shortTitle: "Deploy",
    question: "배포와 운영에서 확인해야 할 조건은 무엇인가요?",
    helper: "도메인, 환경변수, 빌드 확인, QA 시나리오를 적어주세요.",
    placeholder: "예: Vercel 배포, .env.local 관리, 모바일 QA, README 업데이트",
  },
];

export const emptyProject: Project = {
  idea: "",
  target: "",
  serviceType: "",
  references: "",
  mvpFeatures: "",
  screens: "",
  dataApi: "",
  architecture: "",
  promptPreference: "",
  deployment: "",
};
